<?php

use Corviz\Crow\Crow;

if (!is_dir(__DIR__.'/../vendor')) {
    die('You have to run <strong>$ composer install</strong> first!');
}

//In a real world application, this should be loaded automatically by composer
require __DIR__.'/../vendor/autoload.php';
require __DIR__.'/ExampleComponent.php';
require __DIR__.'/packages/example-package/boot.php';

//This is what really matters:
Crow::setDefaultPath(__DIR__.'/templates');
Crow::addComponentsNamespace('ExampleApp');
Crow::setCacheFolder(__DIR__.'/cache');


$message = 'This is an example template generated by Crow Template Engine';
$links = [
    ['url' => 'https://corviz.github.io/crow/', 'label' => 'Docs/Examples'],
    ['url' => 'https://github.com/Corviz/crow', 'label' => 'Source Code'],
];
$data = compact('message', 'links');

Crow::render('home', $data);
